FROM node:22-slim


# 作業ディレクトリを指定
WORKDIR /app/frontend

# 依存関係をコピー
COPY ./frontend/package.json ./frontend/package-lock.json  /app/frontend/

# 依存関係をインストール
RUN npm install

# 開発サーバーを起動
CMD ["npm", "run", "dev"]
